# Generated by Django 3.0.5 on 2020-04-13 22:11

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('key', models.CharField(max_length=128, validators=[django.core.validators.RegexValidator(code='invalid_key', message='Key must be Alphanumeric', regex='^[\\d\\w]*$')])),
                ('type', models.CharField(choices=[('TEXT', 'Text'), ('TEXTAREA', 'Textarea'), ('FILE', 'File')], max_length=12)),
                ('value', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, max_length=255, null=True, upload_to='')),
                ('show_id', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'config_value',
            },
        ),
        migrations.AddConstraint(
            model_name='configvalue',
            constraint=models.UniqueConstraint(fields=('key', 'show_id'), name='unique_key_show'),
        ),
    ]
