# Generated by Django 3.0.5 on 2023-01-24 17:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configvalue',
            name='selection_plan_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='configvalue',
            name='key',
            field=models.CharField(max_length=128, validators=[django.core.validators.RegexValidator(code='invalid_key', message='Key must be Alphanumeric', regex='^[\\d\\w\\.]*$')]),
        )
    ]
