# Generated by Django 3.0.5 on 2023-01-26 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20230124_1710'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='configvalue',
            name='unique_key_show',
        ),
        migrations.AddConstraint(
            model_name='configvalue',
            constraint=models.UniqueConstraint(fields=('key', 'show_id', 'selection_plan_id'), name='unique_key_show_selection_plan'),
        ),
    ]
