# Generated by Django 3.0.5 on 2024-01-12 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20230126_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configvalue',
            name='type',
            field=models.CharField(choices=[('TEXT', 'Text'), ('TEXTAREA', 'Textarea'), ('FILE', 'File'), ('HEX_COLOR', 'Hex Color')], max_length=12),
        ),
    ]
