# Generated by Django 3.0.5 on 2024-01-15 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20240112_1358'),
    ]

    operations = [
        migrations.RunSQL("ALTER TABLE config_values MODIFY type ENUM('TEXT', 'TEXTAREA', 'FILE', 'HEX_COLOR') NULL DEFAULT 'TEXTAREA';")
    ]
